[req]
distinguished_name = req_distinguished_name
req_extensions = v3_req
 
[req_distinguished_name]
countryName = CD
countryName_default = CD
stateOrProvinceName = SC
stateOrProvinceName_default = SC
localityName = China
localityName_default = China
organizationalUnitName  = GOOGLE
organizationalUnitName_default  = GOOGLE
commonName = *.tpo.google.com
commonName_max  = 64
 
[ v3_req ]
# Extensions to add to a certificate request
basicConstraints = CA:false
keyUsage = nonRepudiation, digitalSignature, keyEncipherment
subjectAltName = @alt_names
 
# 配置该证书的可用域名
[alt_names]
DNS.1 = meeting.tpo.google.com
DNS.2 = meeting-outer.tpo.google.com
DNS.3 = livekit-meet.tpo.google.com
DNS.4 = livekit-server.tpo.google.com
DNS.5 = livekit-server-dev.tpo.google.com
